---
# service: demo
apiVersion: v1
kind: Service
metadata:
  name: demo-vip
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
  - name: demo
    port: 9001
    protocol: TCP
    targetPort: svcport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: framework:v1.2
        command: ["/usr/bin/uvframe", "start", "/etc/uvframe/demo.yml"]
        ports:
        - containerPort: 9001
          name: svcport
          protocol: TCP
