# images: <sunquana/archlinux>
FROM archlinux/archlinux:latest

LABEL maintainer="ForrestSu <sunquana@gmail.com>"

ENV TZ=Asia/Shanghai \
    HOME=/home/sq

WORKDIR /home/sq

COPY tmux.conf $HOME/.tmux.conf
COPY zshrc $HOME/.custom_rc
COPY vimrc $HOME/.vimrc
COPY install-dependencies.sh .

## use aliyun source, and update software package cache, and import Chinese PGP keys
# RUN sed -i '1i\Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist \
RUN echo -e 'Server = http://mirrors.aliyun.com/archlinux/$repo/os/$arch\n' >  /etc/pacman.d/mirrorlist \
    && echo -e '[archlinuxcn]\nServer = https://mirrors.aliyun.com/archlinuxcn/$arch' >> /etc/pacman.conf \
    && pacman -Syy \
    && pacman-key --init \
    && pacman-key --lsign-key "farseerfc@archlinux.org" \
    && pacman --noconfirm --needed -S --asdeps archlinuxcn-keyring

RUN ./install-dependencies.sh
RUN pacman --noconfirm -Scc \
    && mv ~/.custom_rc ~/.zshrc \
    # && echo "export PROMPT='[%n@%m]%~%# '" >> $HOME/.zshrc \
    && echo "$(cat /usr/share/oh-my-zsh/zshrc ; cat ~/.zshrc)" > ~/.zshrc \
    && sed -i 's/%c/%d/' /usr/share/oh-my-zsh/themes/robbyrussell.zsh-theme \
    && usermod -s /bin/zsh root \
    && ldconfig

CMD ["zsh"]
