FROM centos/devtoolset-7-toolchain-centos7
ENV TZ=Asia/Shanghai
WORKDIR  /home/frame
USER 0
COPY pkgs .
RUN mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo_bak \
  && curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
  && yum makecache \
  && yum -y install epel-release \
  && sed -i '/tsflags=nodocs/s/^/#/' /etc/yum.conf \
  && yum install -y htop iotop iftop sysstat strace ethtool bwm-ng dsniff net-tools nc \
    rsync pinfo lsof perf tree wget unzip p7zip file man man-pages  zsh make git vim \
    openssl openssl-devel curl-devel libuuid-devel doxygen \
  && yum -y install https://centos7.iuscommunity.org/ius-release.rpm \
  && yum install -y tmux2u \
  && yum clean all -y \
  && yum localinstall *.rpm -y \
  && rm -rf *.rpm \
  && ldconfig \
  && usermod -s /bin/zsh root

COPY tmux.conf $HOME/.tmux.conf
## USER 1001
CMD ["zsh"]
