# images: <sunquana/archlinux>
FROM archlinux/base

LABEL maintainer="ForrestSu <sunquana@gmail.com>"

ENV TZ=Asia/Shanghai \
    HOME=/home/sunquan

WORKDIR /home/sunquan

COPY tmux.conf $HOME/.tmux.conf
COPY zshrc $HOME/.custom_rc
## use tsinghua source, and update software package cache, and Import Chinese PGP Keys
RUN sed -i '1i\Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist \
    && echo -e '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch' >> /etc/pacman.conf \
    && pacman -Syy && pacman-key --init && pacman --noconfirm --needed -S --asdeps archlinuxcn-keyring \
    && pacman --noconfirm --needed -S --asdeps \
      which \
      inetutils ethtool net-tools iproute2 bwm-ng dsniff \
      htop iotop iftop sysstat \
      strace nmap lsof \
      rsync pinfo perf parallel tree wget unzip p7zip file \
      man man-pages \
      make cmake \
      gcc gdb doxygen \
      tmux git vim awk zsh oh-my-zsh-git fish openssh \
      automake autoconf libtool ninja fakeroot \
      zlib leveldb openssl libuv zeromq tinyxml2 nanomsg protobuf grpc gflags gtest \
    && pacman --noconfirm -Scc \
    && cp /usr/share/oh-my-zsh/zshrc ~/.zshrc && cat ~/.custom_rc >> ~/.zshrc && rm ~/.custom_rc \
    && sed -i 's/%c/%d/' /usr/share/oh-my-zsh/themes/robbyrussell.zsh-theme \
    && usermod -s /bin/zsh root \
    && ldconfig
CMD ["zsh"]
