# images: <sunquana/archlinux>
FROM archlinux/base

LABEL maintainer="ForrestSu <sunquana@gmail.com>"

ENV TZ=Asia/Shanghai \
    HOME=/home/sunquan

WORKDIR /home/sunquan

COPY tmux.conf $HOME/.tmux.conf
COPY zshrc $HOME/.custom_rc
COPY vimrc $HOME/.vimrc

## use tsinghua source, and update software package cache, and Import Chinese PGP Keys
RUN sed -i '1i\Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist \
    && echo -e '[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch' >> /etc/pacman.conf \
    && pacman -Syy && pacman-key --init && pacman --noconfirm --needed -S --asdeps archlinuxcn-keyring \
    && pacman --noconfirm --needed -S --asdeps \
      inetutils iputils ethtool net-tools iproute2 bwm-ng dsniff \
      nmap \
      which \
      ascii \
      htop iotop iftop sysstat \
      lsof \
      strace \
      rsync \
      tcpdump traceroute \
      perf \
      iperf iperf3 \
      parallel \
      pinfo \
      tree \
      wget \
      unzip \
      p7zip \
      file \
      dos2unix \
      man man-pages \
      make cmake \
      tmux git vim awk zsh fish openssh \
      gcc gdb doxygen \
      cloc \
      patchelf \
      oh-my-zsh-git \
      automake autoconf libtool ninja fakeroot \
      jemalloc \
      zlib leveldb openssl libuv zeromq tinyxml2 nanomsg protobuf grpc gflags gtest \
    && pacman --noconfirm -Scc \
    && mv ~/.custom_rc ~/.zshrc \
    # && echo "export PROMPT='[%n@%m]%~%# '" >> $HOME/.zshrc \
    && echo "$(cat /usr/share/oh-my-zsh/zshrc ; cat ~/.zshrc)" > ~/.zshrc \
    && sed -i 's/%c/%d/' /usr/share/oh-my-zsh/themes/robbyrussell.zsh-theme \
    && usermod -s /bin/zsh root \
    && ldconfig
CMD ["zsh"]
