FROM ubuntu:25.04 AS dev

LABEL maintainer="ForrestSu <sunquana@gmail.com>"

ENV TZ=Asia/Shanghai \
    HOME=/home/sq

WORKDIR /home/sq

COPY tmux.conf $HOME/.tmux.conf
COPY zshrc $HOME/.custom_rc
COPY vimrc $HOME/.vimrc
COPY sources.list $HOME/sources.list
COPY install-dependencies.sh .

## use tsinghua source
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && mv $HOME/sources.list /etc/apt/ \
    && apt-get update && apt-get -y upgrade \
    && apt-get install -y apt-utils build-essential

## Unminimize
RUN yes | unminimize

RUN ./install-dependencies.sh \
    && cat ~/.custom_rc >> ~/.zshrc && rm ~/.custom_rc \
    && usermod -s /bin/zsh root \
    && ldconfig
CMD ["zsh"]
