version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit:3.6.1
    hostname: 9.135.97.40
    volumes:
      # /data/gerrit 更改为自己的路径
      - /data/gerrit/git:/var/gerrit/git
      - /data/gerrit/index:/var/gerrit/index
      - /data/gerrit/cache:/var/gerrit/cache
      - /data/gerrit/db:/var/gerrit/db
      - /data/gerrit/etc:/var/gerrit/etc
    ports:
      - "29418:29418"
      - "8080:8080"
